package com.catoni;

import java.util.Collections;

import com.catoni.models.enums.MoveTypes;
import com.catoni.models.enums.ResourceTypes;
import com.catoni.models.*;


rule "Build House"
    salience 1
    when

        $is: InputState(
            resources.contains(ResourceTypes.WOOD) && resources.contains(ResourceTypes.CLAY)
            && resources.contains(ResourceTypes.SHEEP) && resources.contains(ResourceTypes.GRAIN)
            )
        $m: Move()
    then
        System.out.println("Building house!");
        $m.setMove(MoveTypes.BUILD_HOUSE);
        update($m);
end

rule "Build Hotel"
    salience 2
    when
        $is: InputState( Collections.frequency(resources, ResourceTypes.ROCK) == 3 && Collections.frequency(resources, ResourceTypes.GRAIN) == 2 )
        $m: Move( move == MoveTypes.MONOPOLY_GRAIN)

    then
        System.out.println("Building hotel!");
        $m.setMove(MoveTypes.BUILD_HOTEL);
        update($m);
end

rule "Build Road"
    salience 3
    when

        $is: InputState(
                resources.contains(ResourceTypes.WOOD) && resources.contains(ResourceTypes.CLAY)
            )
        $m: Move()
    then
        $m.setMove(MoveTypes.BUILD_ROAD);
        update($m);
end

rule "Buy Crazy if you have a lot rocks and grains"
    salience 4
    when

        $is: InputState(
            resources.contains(ResourceTypes.SHEEP) &&
            resources.contains(ResourceTypes.GRAIN) &&
            resources.contains(ResourceTypes.ROCK) &&
            playerStates.get("bot").getResourceChances().get(ResourceTypes.ROCK) > 0.07 &&
            playerStates.get("bot").getResourceChances().get(ResourceTypes.GRAIN) > 0.07
            )
        $m: Move()

    then

        $m.setMove(MoveTypes.BUY_CRAZY);
        update($m);
end