package com.catoni;
import com.catoni.models.enums.*;
import com.catoni.models.*;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Arrays;
import java.util.List;
import java.util.HashMap;
import java.util.Map;

rule "Set points to 7"
  no-loop
  salience 10000000
  lock-on-active true
  when
    $gs: GlobalState()
    eval(7 > 0)
    $is: InputState()
    $m: Move()
  then
    modify($gs) { setPointsForWin(7)}
    if ($is.getPlayerStates().get("bot").getTotalGamePoints("bot") >= 7) {
      $m.addMove(MoveTypes.WIN_GAME);
    }
end


