package com.catoni;

import com.catoni.models.enums.*;
import com.catoni.models.*;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Arrays;
import java.util.List;
import java.util.concurrent.ThreadLocalRandom;
import java.util.HashMap;
import java.util.Map;

rule "Available house position"
  lock-on-active true
  salience 100
  when
    $is: InputState()
    
    accumulate(
        Building($t: this) from $is.position.getAvailableBuildingSpotsForPlayer("bot"),
        $available: collectList($t)
    )

    eval($available.size() >= 1)

    Number($val: doubleValue) from accumulate(
        Building($t: this, status == Status.FREE) from $available,
        max($t.getSumOfChances())
    )

    $b: Building(status == Status.FREE && getSumOfChances() == $val) from $available

    $m: Move()

  then
    $m.addMove(MoveTypes.POTENTIAL_BUILD_HOUSE);
    $m.addBuilding($b);
    update($m);

end