package com.catoni;

import java.util.Collections;

import com.catoni.models.enums.MoveTypes;
import com.catoni.models.enums.ResourceTypes;
import com.catoni.models.enums.BuildingTypes;
import com.catoni.models.enums.Status;
import com.catoni.models.*;
import com.catoni.models.dto.*;
import java.lang.Number;


rule "Build House and Road Start"
    salience 1
    when
       $p: Position()

       Number($val: doubleValue) from accumulate(
            Building($t: this, status == Status.FREE) from $p.buildings,
            max($t.getSumOfChances())
       )

       $b: Building(getSumOfChances() == $val) from $p.buildings

       Number($eval: doubleValue) from accumulate(
            Building($t: this, status == Status.FREE,
                (row == $b.row && column == $b.column + 2) ||
                (row == $b.row && column == $b.column - 2) ||
                (row == $b.row - 1 && column == $b.column - 2) ||
                (row == $b.row - 1 && column == $b.column) ||
                (row == $b.row + 1 && column == $b.column) ||
                (row == $b.row + 1 && column == $b.column + 2)
                ) from $p.buildings,
            max($t.getSumOfChances())
       )
       $br: Building(getSumOfChances() == $eval) from $p.buildings

       $r : Road() from $p.getRoadTowardsBuilding($b, $br)

       $dtoB: BuildingDto()
       $dtoR: RoadDto()
    then
        $dtoB.setRow($b.getRow());
        $dtoB.setCol($b.getColumn());
        $dtoB.setPlayerName("bot");
        $dtoB.setType(BuildingTypes.HOUSE);
        update($dtoB);
        $dtoR.setRow1($r.getRow1());
        $dtoR.setCol1($r.getCol1());
        $dtoR.setRow2($r.getRow2());
        $dtoR.setCol2($r.getCol2());
        $dtoR.setPlayer("bot");
        update($dtoR);
end
