package com.catoni;

import com.catoni.models.enums.*;
import com.catoni.models.*;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Arrays;
import java.util.List;
import java.util.concurrent.ThreadLocalRandom;
import java.util.HashMap;
import java.util.Map;
import com.catoni.models.dto.*;
import java.lang.Number;

declare TooManyOffersEvent
    @role(event)
    cnt: Integer
end

declare TradeAcceptedEvent
    @role(event)
    player: String
end

declare TradeDeclinedEvent
    @role(event)
    cnt: Integer
end

rule "Offer player trade if missing resource"
    lock-on-active true
    salience -90
    when
        $is: InputState(
            resources.size() >= 4
        )
        $m: Move()

        Number($wood: intValue) from accumulate(
            ResourceTypes($t: this, $t == ResourceTypes.WOOD) from $is.resources,
            count($t)
        )

        Number($clay: intValue) from accumulate(
            ResourceTypes($t: this, $t == ResourceTypes.CLAY) from $is.resources,
            count($t)
        )

        Number($grain: intValue) from accumulate(
            ResourceTypes($t: this, $t == ResourceTypes.GRAIN) from $is.resources,
            count($t)
        )


        Number($sheep: intValue) from accumulate(
            ResourceTypes($t: this, $t == ResourceTypes.SHEEP) from $is.resources,
            count($t)
        )


        Number($rock: intValue) from accumulate(
            ResourceTypes($t: this, $t == ResourceTypes.ROCK) from $is.resources,
            count($t)
        )

        $offer: TradeOffer() from $m.trade.getTradeOffer()

        Number($tradeCount: intValue < 2) from accumulate(
            $o: TradeOffer( this meets[2m] $offer ),
            count($o)
        )

        not(TooManyOffersEvent(cnt > 2))
        not(TradeDeclinedEvent(cnt >= 2))
    then
        System.out.println($tradeCount);
        if($tradeCount >= 2){
            insert(new TooManyOffersEvent(3));
            $m.addMove(MoveTypes.END_TURN);
            update($m);
        }
        Map<ResourceTypes, Integer> offer = new HashMap<>();
        Map<ResourceTypes, Integer> receive = new HashMap<>();
        List<ResourceTypes> excess = new ArrayList<>();
        ResourceTypes wanted = null;

        if($wood >= 1 && $clay >= 1 && $grain >= 1 && $sheep == 0){
            excess = $is.findExcess($wood, $clay, $grain, $sheep, $rock, BuildingTypes.HOUSE, ResourceTypes.SHEEP);
            wanted = ResourceTypes.SHEEP;

            System.out.println("OFFER" + excess);
            System.out.println("FOR SHEEP");

        }
        else if($wood >= 1 && $clay >= 1 && $grain == 0 && $sheep >= 1){
            excess = $is.findExcess($wood, $clay, $grain, $sheep, $rock, BuildingTypes.HOUSE, ResourceTypes.GRAIN);
            wanted = ResourceTypes.GRAIN;

            System.out.println("OFFER" + excess);
            System.out.println("FOR GRAIN");
        }
        else if($wood >= 1 && $clay == 0 && $grain >= 1 && $sheep >= 1){
            excess = $is.findExcess($wood, $clay, $grain, $sheep, $rock, BuildingTypes.HOUSE, ResourceTypes.CLAY);
            wanted = ResourceTypes.CLAY;

            System.out.println("OFFER" + excess);
            System.out.println("FOR CLAY");
        }
        else if($wood == 0 && $clay >= 1 && $grain >= 1 && $sheep >= 1){
            excess = $is.findExcess($wood, $clay, $grain, $sheep, $rock, BuildingTypes.HOUSE, ResourceTypes.WOOD);
            wanted = ResourceTypes.WOOD;

            System.out.println("OFFER" + excess);
            System.out.println("FOR WOOD");
        }
        else if($rock >= 3 && $grain <= 1){
            excess = $is.findExcess($wood, $clay, $grain, $sheep, $rock, BuildingTypes.HOTEL, ResourceTypes.GRAIN);
            wanted = ResourceTypes.GRAIN;

            System.out.println("OFFER" + excess);
            System.out.println("FOR GRAIN");
        }
        else if($rock <= 2 && $grain >= 2){
            excess = $is.findExcess($wood, $clay, $grain, $sheep, $rock, BuildingTypes.HOTEL, ResourceTypes.ROCK);
            wanted = ResourceTypes.ROCK;

            System.out.println("OFFER" + excess);
            System.out.println("FOR ROCK");
        }
        if(excess.size() >= 1 && wanted != null){

            offer.put(excess.get(0), 1);
            if($tradeCount > 0 && excess.size() >= 2){
                if(excess.get(1) == excess.get(0)){
                    offer.replace(excess.get(0), 2);
                }
                else{
                    offer.put(excess.get(1), 1);
                }
            }
            receive.put(wanted, 1);
            $offer.setOffer(offer);
            $offer.setReceive(receive);
            insert($offer);
            $m.addMove(MoveTypes.OFFER_TRADE_WITH_PLAYER);
            //update($offer);
            update($m);
        }
end

rule "Trade accepted"
    no-loop
    salience 500
    when
        $is: InputState()
        $m: Move( trade.getAcceptedTrade().size() > 0 && moveList.get(moveList.size()-1) == MoveTypes.OFFER_TRADE_WITH_PLAYER )

    then
        System.out.println($m.trade.getAcceptedTrade().get(0) + " Accepted the trade");

        Map.Entry<ResourceTypes,Integer> entry = $m.trade.getTradeOffer().getReceive().entrySet().iterator().next();
        ResourceTypes key = entry.getKey();
        Integer value = entry.getValue();
        $is.getResources().add(key);

        List<ResourceTypes> away = new ArrayList<>();

        for(Map.Entry<ResourceTypes,Integer> entryOff: $m.trade.getTradeOffer().getOffer().entrySet()){
            ResourceTypes keyO = entryOff.getKey();
            Integer valueO = entryOff.getValue();
            for(int i = 0; i < valueO; i++){
                $is.getResources().remove(keyO);
                System.out.println("REMOVED: " + keyO);
                away.add(keyO);
            }
        }
        State previousState = $is.getPlayerStates().get($m.trade.getAcceptedTrade().get(0));
        previousState.addResources(away);
        previousState.getResources().remove(key);
        $is.getPlayerStates().replace($m.trade.getAcceptedTrade().get(0), previousState);

        $m.addMove(MoveTypes.EXECUTE_TRADE);
        update($is);
        update($m);
end

rule "Trade declined"
    lock-on-active true
    salience 499
    when
        $is: InputState()
        $m: Move(moveList.get(moveList.size()-1) == MoveTypes.OFFER_TRADE_WITH_PLAYER && trade.getStatus() == TradeStatus.DECLINED)
    then
        $m.addMove(MoveTypes.DECLINE_TRADE);
        int declineCount = Collections.frequency($m.moveList, MoveTypes.OFFER_TRADE_WITH_PLAYER);
        insert(new TradeDeclinedEvent(declineCount));
        insert($m.trade.getTradeOffer());
        if(declineCount >= 2){
            $m.addMove(MoveTypes.END_TURN);
            update($m);
        }
        System.out.println("Trade declined");
        update($m);
end


rule "Mairtime trade"
    salience -80
    when
        $is: InputState()

        Number($wood: intValue) from accumulate(
            ResourceTypes($t: this, $t == ResourceTypes.WOOD) from $is.resources,
            count($t)
        )

        Number($clay: intValue) from accumulate(
            ResourceTypes($t: this, $t == ResourceTypes.CLAY) from $is.resources,
            count($t)
        )

        Number($grain: intValue) from accumulate(
            ResourceTypes($t: this, $t == ResourceTypes.GRAIN) from $is.resources,
            count($t)
        )


        Number($sheep: intValue) from accumulate(
            ResourceTypes($t: this, $t == ResourceTypes.SHEEP) from $is.resources,
            count($t)
        )


        Number($rock: intValue) from accumulate(
            ResourceTypes($t: this, $t == ResourceTypes.ROCK) from $is.resources,
            count($t)
        )

        eval($wood >= 6 || $clay >= 6 || $rock >= 7 || $grain >= 6 || $sheep >= 5)

        $m: Move()

    then
        int excessNeeded = 4;
        if($is.getDistanceToHarbor() == 0){
            excessNeeded = 3;
        }

        State botState = $is.getPlayerStates().get("bot");

        ResourceTypes lowestChance = ResourceTypes.CLAY;
        double lowest = 2;

        for(Map.Entry<ResourceTypes,Double> rc: botState.getResourceChances().entrySet()){
            ResourceTypes k = rc.getKey();
            Double v = rc.getValue();
            if(v < lowest){
                lowest = v;
                lowestChance = k;
            }
        }

        System.out.println("Lowest chance of: " + lowest + " for resource: " + lowestChance);

        if($sheep >= 5){
            System.out.println("TOO MUCH SHEEP -> DO MAIRTIME TRADE");
            $m.addMove(MoveTypes.OFFER_TRADE_WITH_BANK);
            for(int i = 0; i < excessNeeded; i++){
                botState.getResources().remove(ResourceTypes.SHEEP);
            }
            List<ResourceTypes> prev = botState.getResources();
            prev.add(lowestChance);

            $is.setResources(prev);

            update($is);
            update($m);
        }
        if($rock >= 7){
            System.out.println("TOO MUCH ROCKS -> DO MAIRTIME TRADE");
            $m.addMove(MoveTypes.OFFER_TRADE_WITH_BANK);
            for(int i = 0; i < excessNeeded; i++){
                botState.getResources().remove(ResourceTypes.ROCK);
            }
            List<ResourceTypes> prev = botState.getResources();
            prev.add(lowestChance);

            $is.setResources(prev);

            update($is);
            update($m);
        }
        if($grain >= 6){
            System.out.println("TOO MUCH GRAIN -> DO MAIRTIME TRADE");
            $m.addMove(MoveTypes.OFFER_TRADE_WITH_BANK);
            for(int i = 0; i < excessNeeded; i++){
                botState.getResources().remove(ResourceTypes.GRAIN);
            }
            List<ResourceTypes> prev = botState.getResources();
            prev.add(lowestChance);

            $is.setResources(prev);

            update($is);
            update($m);
        }
        if($wood >= 6){
            System.out.println("TOO MUCH WOOD -> DO MAIRTIME TRADE");
            $m.addMove(MoveTypes.OFFER_TRADE_WITH_BANK);
            for(int i = 0; i < excessNeeded; i++){
                botState.getResources().remove(ResourceTypes.WOOD);
            }
            List<ResourceTypes> prev = botState.getResources();
            prev.add(lowestChance);

            $is.setResources(prev);

            update($is);
            update($m);
        }
        if($clay >= 6){
            System.out.println("TOO MUCH CLAY -> DO MAIRTIME TRADE");
            $m.addMove(MoveTypes.OFFER_TRADE_WITH_BANK);
            for(int i = 0; i < excessNeeded; i++){
                botState.getResources().remove(ResourceTypes.ROCK);
            }
            List<ResourceTypes> prev = botState.getResources();
            prev.add(lowestChance);

            $is.setResources(prev);

            update($is);
            update($m);
        }
end

rule "End turn"
    no-loop
    salience -1500
    when
        $is: InputState()
        $m: Move( moveList.get(moveList.size()-1) != MoveTypes.OFFER_TRADE_WITH_PLAYER && moveList.get(moveList.size()-1) != MoveTypes.END_TURN)
    then
        $m.addMove(MoveTypes.END_TURN);
        update($m);
end
