package com.catoni.models.enums;

public enum MoveTypes {
    START_TURN,
    END_TURN,

    DRAW_WOOD,
    DRAW_CLAY,
    DRAW_GRAIN,
    DRAW_SHEEP,
    DRAW_ROCK,

    BUILD_HOUSE,
    BUILD_HOTEL,
    BUILD_ROAD,
    BUY_CRAZY,

    PLAY_KNIGHT,
    PLAY_ROAD_BUILDING,
    PLAY_YEAR_OF_PLENTY,
    PLAY_MONOPOLY,

    MONOPOLY_WOOD,
    MONOPOLY_CLAY,
    MONOPOLY_GRAIN,
    MONOPOLY_SHEEP,
    MONOPOLY_ROCK,

    OFFER_TRADE_WITH_BANK,
    OFFER_TRADE_WITH_PLAYER
}
